# enable h2 : http://localhost:8080/h2-console
# JDBC URL : jdbc:h2:mem:testdb
spring:
  profiles:
    active: local # 기본 환경 선택

# local 환경
---
spring:
  profiles: local
  datasource:
    data: classpath:data-h2.sql # 시작할때 실행시킬 script
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
      path: /h2-console
#handlebars:
#  enabled: true
#  prefix: classpath:templates/
#  suffix: .hbs