# enable h2 : http://localhost:8080/h2-console
# JDBC URL : jdbc:h2:mem:testdb
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
#handlebars:
#  enabled: true
#  prefix: classpath:templates/
#  suffix: .hbs